if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/murakami.katsutoshi/google-cloud-sdk/path.bash.inc' ]; then source '/Users/murakami.katsutoshi/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/murakami.katsutoshi/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/murakami.katsutoshi/google-cloud-sdk/completion.bash.inc'; fi
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
