brew 'git'
brew 'vim', args: ['with-lua', 'HEAD']
brew 'hub'
brew 'wget'
brew 'nmap'
brew 'ruby-build'
brew 'rbenv'
brew 'mysql'
brew 'bash-completion'
brew 'terraform'
brew 'jq'
brew 'awscli'
brew 'heroku-toolbelt'
brew 'tmux'
brew 'coreutils'
